### ISSUE TITLE
谢谢作者，安装成功！建议能否在安装时添加回落到其他网站？

### ISSUE THREAD

**Issue by zhukady** [shell-script/naivecaddy#4]
我自行添加了：
file_server {
                        root /usr/local/bin/naivecaddy/wwwhtml
                }

        }
        reverse_proxy  https://abc.com  {
                 header_up  Host  {upstream_hostport}
                 header_up  X-Forwarded-Host  {host}
        }
}

打开 abc.com 网页，显示：auth failed (apdog v1.21.3465, caddy v2.6.1)

**Comment by 1715173329** [comment]
DO NOT ABUSE ISSUE.
You can setup whatever content you like, but this is not something I need to take care.
