### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by akaagiao1** [shell-script/naivecaddy#6]
打开搭建网站显示
auth failed (apdog v1.21.3465, caddy v2.6.1)
配置文件
file_server {
                        root /usr/local/bin/naivecaddy/wwwhtml
                }

        }
        reverse_proxy  https://@@@.com  {
                 header_up  Host  {upstream_hostport}
                 header_up  X-Forwarded-Host  {host}
        }
}
可否添加一个自定义伪装域名😁

**Comment by 1715173329** [comment]
https://github.com/shell-script/naivecaddy/issues/4#issuecomment-1272539752
